# Understanding Backpropagation

## Import Numpy
- For matrix calculation

In [1]:
import numpy as np

## Softmax Implementation

In [2]:
def softmax(arr):    
    return np.exp(arr)/np.sum(np.exp(arr))

In [3]:
softmax(np.array([2,4,5]))

array([0.03511903, 0.25949646, 0.70538451])

## Sigmoid Implementation

In [4]:
def sigmoid(arr):
    return (1/(1+np.exp(-arr)))

In [5]:
sigmoid(np.array([2,4,5]))

array([0.88079708, 0.98201379, 0.99330715])

## ReLU (Rectified Linear Unit) Implementation

In [6]:
def RELU(arr):
    return np.maximum(0.0,arr)

In [7]:
RELU([2,4,5])

array([2., 4., 5.])

## A simple perceptron
- A perceptron is a single layer neural network

 ### output = sigmoid(W*X+B)

In [8]:
def perceptron(X):
    print(X.shape)
    w=np.random.rand(X.shape[0])
    b=10
    return sigmoid(np.array([b+np.dot(X.T,w)]))

In [9]:
perceptron(np.array([2,4,5]))

(3,)


array([0.99999992])

## Initializing Inputs, Target and Weights(for each layer)

- Input nodes : 3 
- Hidden nodes : 2
- Output nodes : 1

In [10]:
x = np.array([0.5, 0.1, -0.2])
target = 0.6
learning_rate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])

weights_hidden_output = np.array([0.1, -0.3])

## Forward Pass

In [11]:
hidden_layer_input = np.dot(x,weights_input_hidden)

In [12]:
hidden_layer_output = sigmoid(hidden_layer_input)

In [13]:
print(hidden_layer_output)

[0.55971365 0.38698582]


In [14]:
output_layer_in = np.dot(hidden_layer_output,weights_hidden_output)
output = sigmoid(output_layer_in)

In [15]:
print(output)

0.48497343084992534


## BackPropagation

In [16]:
error = (output-target)

In [17]:
# calculate error gradient for output layer
del_err_output = error * output * (1-output)

# calculate error gradient for hidden layer
del_err_hidden = np.dot(del_err_output, weights_hidden_output) * hidden_layer_output * (1 - hidden_layer_output)

# calculate change in weights for hidden layer to output layer
delta_w_h_o = learning_rate * del_err_output * hidden_layer_output

# calculate change in weights for input layer to hidden layer
delta_w_i_o = learning_rate * del_err_hidden * x[:,None]

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_o)


Change in weights for hidden layer to output layer:
[-0.00804047 -0.00555918]
Change in weights for input layer to hidden layer:
[[-1.77005547e-04  5.11178506e-04]
 [-3.54011093e-05  1.02235701e-04]
 [ 7.08022187e-05 -2.04471402e-04]]
